name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hybridz:
    name: HybridZ Relaxed
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r setup/main_requirements.txt

      - name: Run HybridZ verification
        run: |
          cd verifier/
          python main.py \
            --verifier hybridz \
            --method hybridz_relaxed \
            --model_path ../models/Sample_models/MNIST/small_relu_mnist_cnn_model_1.onnx \
            --dataset mnist --spec_type local_lp \
            --start 0 --end 1 --epsilon 0.01 --norm inf \
            --relaxation_ratio 1.0 \
            --mean 0.1307 --std 0.3081 \
            --ci