name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hybridz:
    name: HybridZ Relaxed
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
          miniforge-variant: Miniforge3
          use-mamba: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgmp-dev libmpfr-dev

      - name: Set up ACT environments
        shell: bash -l {0}
        run: |
          cd .github/
          source setup_ci_main.sh

      - name: Run HybridZ verification
        shell: bash -l {0}
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate act-main
          cd verifier/
          python main.py \
            --verifier hybridz \
            --method hybridz_relaxed \
            --model_path ../models/Sample_models/MNIST/small_relu_mnist_cnn_model_1.onnx \
            --dataset mnist --spec_type local_lp \
            --start 0 --end 1 --epsilon 0.01 --norm inf \
            --relaxation_ratio 1.0 \
            --mean 0.1307 --std 0.3081 \
            --ci

  abcrown:
    name: ABCrown
    runs-on: ubuntu-22.04
    needs: hybridz
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
          miniforge-variant: Miniforge3
          use-mamba: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgmp-dev libmpfr-dev

      - name: Set up ACT environments
        shell: bash -l {0}
        run: |
          cd .github/
          source setup_ci_abcrown.sh

      - name: Patch ABCrown submodule
        run: |
          INIT_FULL_PATH="modules/abcrown/complete_verifier/__init__.py"
          if grep -q "^from abcrown import ABCROWN" "$INIT_FULL_PATH"; then
            sed -i 's/^from abcrown import ABCROWN/# from abcrown import ABCROWN/' "$INIT_FULL_PATH"
          fi

      - name: Run ABCrown verification
        shell: bash -l {0}
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate act-abcrown
          cd verifier/
          python main.py \
            --verifier abcrown \
            --method alpha_beta \
            --model_path ../models/Sample_models/MNIST/small_relu_mnist_cnn_model_1.onnx \
            --dataset mnist --spec_type local_lp \
            --start 0 --end 1 --epsilon 0.1 --norm inf \
            --mean 0.1307 --std 0.3081